_prefs: 
  mapid: bertspaan.dfb0c369
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -96.8555
  - 54.7753
  - 3
description: #LoveWins
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - admin
  - water
maxzoom: 18
minzoom: 1
name: Rainbow World
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
template: ''
